### ISSUE TITLE
Wrong file for 1.2 release

### ISSUE THREAD

**Issue by LlubNek** [KiameV/rimworld-keephandsfeet#1]
You uploaded HandsAndFootware.zip instead of KeepHandsAndFeet.zip (or whatever) here:
https://github.com/KiameV/rimworld-keephandsfeet/releases/tag/current

**Comment by KiameV** [comment]
Thanks for bringing this to my attention. I have stopped support for this mod. I'm recommending people use this mod instead: https://steamcommunity.com/sharedfiles/filedetails/?id=2103563425 (there's a direct download link in the description of that mod if needed)

**Comment by LlubNek** [comment]
Unfortunately that mod hasn't updated to 1.2 yet (last commit was in June:  https://github.com/RimworldFixes/ProstheticNoMissingBodyParts )
